name: "✨ 기능 개발 요청"
description: 새로운 기능 추가나 기존 기능 개선 제안용
title: "[Feature] 제목을 입력해주세요"
labels: ["enhancement", "기능"]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 개발이나 기존 기능 개선을 제안해주세요.

  - type: input
    id: module
    attributes:
      label: 관련 모듈 또는 폴더
      description: 이 기능이 포함되거나 영향을 주는 코드 위치를 알려주세요.
      placeholder: 예) preprocessing, crawler, analysis 등
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 기능 요약
      description: 이 기능이 어떤 역할을 하는지 한 문장으로 설명해주세요.
      placeholder: 예) 댓글 감정 점수에 따라 색상 표시 추가
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 설명
      description: 기능의 작동 방식, 기대 효과, 데이터 흐름 등을 자세히 작성해주세요.
      placeholder: |
        - 입력: 감정 점수 CSV
        - 처리: 점수 범위별로 색상 지정
        - 출력: 시각화 결과 HTML
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 참고자료 / 관련 코드
      description: 참고한 링크, 예시 코드, 이슈 번호 등을 입력해주세요.
    validations:
      required: false